export const FETCH_REACT_SUBREDDITS_POSTS = 'SET_REACT_SUBREDDITS_POSTS';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_REACT_SUBREDDITS_POSTS = 'SET_REACT_SUBREDDITS_POSTS_NULL';

