export const FETCH_POST_ARTICLE_STARTED = 'FETCH_POST_ARTICLE_STARTED';
export const FETCH_POST_ARTICLE_COMPLETED = 'FETCH_POST_ARTICLE_COMPLETED';
export const SET_SUBREDDITS = 'SET_SUBREDDITS';
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
export const CHANGE_INPUT_STRING = 'CHANGE_INPUT_STRING';
